// articles.js
const articles = [
    {
      id: 1,
      author: "Matthew Futterman",
      title: "At the 2024 Paris Olympic Games, tennis is as odd a fit as ever",
      content: "Article content 1...",
      imageUrl: "/path/to/image1.jpg",
    },
    {
      id: 2,
      author: "Hafsa Ali, Richard Wright",
      title: "Sport policy in Pakistan",
      content: "Article content 2...",
      imageUrl: "/path/to/image2.jpg",
    },
    {
      id: 3,
      author: "Abid Hussain",
      title: "Pakistan's great fall: How former hockey giant failed Olympic test, again",
      content: "Article content 3...",
      imageUrl: "/path/to/image3.jpg",
    },
    {
      id: 4,
      author: "Matthew Futterman",
      title: "Grit, gold, and glory: Meet the Pakistani athletes going to the Paris 2024 Olympics",
      content: "Article content 4...",
      imageUrl: "/path/to/image4.jpg",
    },
    {
      id: 5,
      author: "Nabila Sarwar",
      title: "Abuse of power influencing sexual harassment behaviour in Pakistani sports",
      content: "Article content 5...",
      imageUrl: "/path/to/image5.jpg",
    },
    {
      id: 6,
      author: "Akbar Ali",
      title: "Sports in Pakistan: 6 Fascinating Insights Into Athletic Culture",
      content: "Article content 6...",
      imageUrl: "/path/to/image6.jpg",
    },
    {
      id: 7,
      author: "Rimzan Ahmed, Y. Gu, Q. Zhang",
      title: "Restrictions on Pakistani Female Students' Participation in Sports: A Statistical Model of Constraints",
      content: "Article content 7...",
      imageUrl: "/path/to/image7.jpg",
    },
    {
      id: 8,
      author: "John Doe",
      title: "The Future of Cricket in Pakistan",
      content: "Article content 8...",
      imageUrl: "/path/to/image8.jpg",
    },
    {
      id: 9,
      author: "Jane Smith",
      title: "The Impact of Social Media on Sports",
      content: "Article content 9...",
      imageUrl: "/path/to/image9.jpg",
    },
    {
      id: 10,
      author: "Ahmed Khan",
      title: "How Technology is Revolutionizing Sports Training",
      content: "Article content 10...",
      imageUrl: "/path/to/image10.jpg",
    },
    {
      id: 11,
      author: "Fatima Tariq",
      title: "The Role of Nutrition in Athlete Performance",
      content: "Article content 11...",
      imageUrl: "/path/to/image11.jpg",
    },
    {
      id: 12,
      author: "Mohammed Ali",
      title: "Exploring the History of Football in Pakistan",
      content: "Article content 12...",
      imageUrl: "/path/to/image12.jpg",
    },
    {
      id: 13,
      author: "Ayesha Aslam",
      title: "Women in Sports: Breaking Barriers in Pakistan",
      content: "Article content 13...",
      imageUrl: "/path/to/image13.jpg",
    },
    {
      id: 14,
      author: "Usman Siddiqui",
      title: "The Economic Impact of Hosting Major Sports Events",
      content: "Article content 14...",
      imageUrl: "/path/to/image14.jpg",
    },
    {
      id: 15,
      author: "Sara Malik",
      title: "Mental Health and Sports: The Untold Story",
      content: "Article content 15...",
      imageUrl: "/path/to/image15.jpg",
    }
  ];
  
  export default articles;
