// src/data/matchData.js

const cricketData = [
  {
    team1: "Pakistan",
    team2: "Bangladesh",
    date: "31 August, 07:00 am",
    venue: "Bangladesh, Cricket Stadium, Bangladesh",
    flag1: "/img/pakistan.jpg",
    flag2: "/img/bangladesh.jpg",
    matchDetails: "1st Test - BAN in PAK, 2 Tests, 2024",
  },
  {
    team1: "India",
    team2: "Australia",
    date: "2 September, 01:00 pm",
    venue: "India, Wankhede Stadium",
    flag1: "/img/india.jpg",
    flag2: "/img/australia.jpg",
    matchDetails: "2nd ODI - AUS in IND, 3 ODIs, 2024",
  },
  {
    team1: "South Africa",
    team2: "England",
    date: "5 September, 04:00 pm",
    venue: "South Africa, Wanderers Stadium",
    flag1: "/img/southafrica.jpg",
    flag2: "/img/england.jpg",
    matchDetails: "3rd T20 - ENG in SA, 3 T20s, 2024",
  },
  {
    team1: "New Zealand",
    team2: "West Indies",
    date: "8 September, 10:00 am",
    venue: "New Zealand, Eden Park",
    flag1: "/img/newzealand.jpg",
    flag2: "/img/westindies.jpg",
    matchDetails: "1st Test - WI in NZ, 2 Tests, 2024",
  },
  {
    team1: "Sri Lanka",
    team2: "Afghanistan",
    date: "11 September, 02:30 pm",
    venue: "Sri Lanka, Pallekele International Stadium",
    flag1: "/img/srilanka.jpg",
    flag2: "/img/afghanistan.jpg",
    matchDetails: "2nd ODI - AFG in SL, 3 ODIs, 2024",
  },
  {
    team1: "Bangladesh",
    team2: "Pakistan",
    date: "15 September, 07:00 am",
    venue: "Pakistan, Gaddafi Stadium",
    flag1: "/img/bangladesh.jpg",
    flag2: "/img/pakistan.jpg",
    matchDetails: "2nd Test - PAK in BAN, 2 Tests, 2024",
  },
  {
    team1: "Australia",
    team2: "India",
    date: "18 September, 01:00 pm",
    venue: "Australia, Melbourne Cricket Ground",
    flag1: "/img/australia.jpg",
    flag2: "/img/india.jpg",
    matchDetails: "1st T20 - IND in AUS, 3 T20s, 2024",
  },
  {
    team1: "England",
    team2: "South Africa",
    date: "21 September, 04:00 pm",
    venue: "England, Lord's",
    flag1: "/img/england.jpg",
    flag2: "/img/southafrica.jpg",
    matchDetails: "1st ODI - SA in ENG, 3 ODIs, 2024",
  },
  {
    team1: "West Indies",
    team2: "New Zealand",
    date: "24 September, 10:00 am",
    venue: "West Indies, Kensington Oval",
    flag1: "/img/westindies.jpg",
    flag2: "/img/newzealand.jpg",
    matchDetails: "2nd Test - NZ in WI, 2 Tests, 2024",
  },
  {
    team1: "Afghanistan",
    team2: "Sri Lanka",
    date: "27 September, 02:30 pm",
    venue: "Afghanistan, Kabul International Stadium",
    flag1: "/img/afghanistan.jpg",
    flag2: "/img/srilanka.jpg",
    matchDetails: "3rd ODI - SL in AFG, 3 ODIs, 2024",
  },
  {
    team1: "Pakistan",
    team2: "India",
    date: "30 September, 01:00 pm",
    venue: "Neutral Venue, Dubai International Stadium",
    flag1: "/img/pakistan.jpg",
    flag2: "/img/india.jpg",
    matchDetails: "Asia Cup Final 2024",
  },
  {
    team1: "New Zealand",
    team2: "Australia",
    date: "3 October, 01:00 pm",
    venue: "New Zealand, Basin Reserve",
    flag1: "/img/newzealand.jpg",
    flag2: "/img/australia.jpg",
    matchDetails: "3rd ODI - AUS in NZ, 3 ODIs, 2024",
  },
  {
    team1: "West Indies",
    team2: "England",
    date: "6 October, 04:00 pm",
    venue: "West Indies, Sabina Park",
    flag1: "/img/westindies.jpg",
    flag2: "/img/england.jpg",
    matchDetails: "3rd T20 - ENG in WI, 3 T20s, 2024",
  },
  {
    team1: "South Africa",
    team2: "Sri Lanka",
    date: "9 October, 02:30 pm",
    venue: "South Africa, Centurion",
    flag1: "/img/southafrica.jpg",
    flag2: "/img/srilanka.jpg",
    matchDetails: "1st Test - SL in SA, 2 Tests, 2024",
  },
  {
    team1: "Bangladesh",
    team2: "Afghanistan",
    date: "12 October, 07:00 am",
    venue: "Bangladesh, Sher-e-Bangla National Stadium",
    flag1: "/img/bangladesh.jpg",
    flag2: "/img/afghanistan.jpg",
    matchDetails: "2nd ODI - AFG in BAN, 3 ODIs, 2024",
  },
];

const footballData = [
  {
    team1: "Team A",
    team2: "Team B",
    date: "1 September, 06:00 pm",
    venue: "Stadium 1",
    flag1: "/img/teama.jpg",
    flag2: "/img/teamb.jpg",
    matchDetails: "Championship Final 2024",
  },
  {
    team1: "Team C",
    team2: "Team D",
    date: "3 September, 08:00 pm",
    venue: "Stadium 2",
    flag1: "/img/teamc.jpg",
    flag2: "/img/teamd.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team E",
    team2: "Team F",
    date: "5 September, 07:00 pm",
    venue: "Stadium 3",
    flag1: "/img/teame.jpg",
    flag2: "/img/teamf.jpg",
    matchDetails: "Cup Quarterfinal 2024",
  },
  {
    team1: "Team G",
    team2: "Team H",
    date: "7 September, 05:00 pm",
    venue: "Stadium 4",
    flag1: "/img/teamg.jpg",
    flag2: "/img/teamh.jpg",
    matchDetails: "Friendly Match 2024",
  },
  {
    team1: "Team I",
    team2: "Team J",
    date: "10 September, 09:00 pm",
    venue: "Stadium 5",
    flag1: "/img/teami.jpg",
    flag2: "/img/teamj.jpg",
    matchDetails: "World Cup Qualifier 2024",
  },
  {
    team1: "Team K",
    team2: "Team L",
    date: "12 September, 08:00 pm",
    venue: "Stadium 6",
    flag1: "/img/teamk.jpg",
    flag2: "/img/teaml.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team M",
    team2: "Team N",
    date: "14 September, 06:00 pm",
    venue: "Stadium 7",
    flag1: "/img/teamm.jpg",
    flag2: "/img/teamn.jpg",
    matchDetails: "Cup Semifinal 2024",
  },
  {
    team1: "Team O",
    team2: "Team P",
    date: "16 September, 04:00 pm",
    venue: "Stadium 8",
    flag1: "/img/teamo.jpg",
    flag2: "/img/teamp.jpg",
    matchDetails: "Friendly Match 2024",
  },
  {
    team1: "Team Q",
    team2: "Team R",
    date: "18 September, 02:00 pm",
    venue: "Stadium 9",
    flag1: "/img/teamq.jpg",
    flag2: "/img/teamr.jpg",
    matchDetails: "International Friendly 2024",
  },
  {
    team1: "Team S",
    team2: "Team T",
    date: "20 September, 05:00 pm",
    venue: "Stadium 10",
    flag1: "/img/teams.jpg",
    flag2: "/img/teamt.jpg",
    matchDetails: "League Match 2024",
  },  
  {
    team1: "Team U",
    team2: "Team V",
    date: "22 September, 07:00 pm",
    venue: "Stadium 11",
    flag1: "/img/teamu.jpg",
    flag2: "/img/teamv.jpg",
    matchDetails: "Cup Final 2024",
  },
  {
    team1: "Team W",
    team2: "Team X",
    date: "24 September, 09:00 pm",
    venue: "Stadium 12",
    flag1: "/img/teamw.jpg",
    flag2: "/img/teamx.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team Y",
    team2: "Team Z",
    date: "26 September, 08:00 pm",
    venue: "Stadium 13",
    flag1: "/img/teamy.jpg",
    flag2: "/img/teamz.jpg",
    matchDetails: "International Friendly 2024",
  },
  {
    team1: "Team AA",
    team2: "Team BB",
    date: "28 September, 06:00 pm",
    venue: "Stadium 14",
    flag1: "/img/teamaa.jpg",
    flag2: "/img/teambb.jpg",
    matchDetails: "World Cup Qualifier 2024",
  },
  {
    team1: "Team CC",
    team2: "Team DD",
    date: "30 September, 04:00 pm",
    venue: "Stadium 15",
    flag1: "/img/teamcc.jpg",
    flag2: "/img/teamdd.jpg",
    matchDetails: "League Match 2024",
  },
];

const basketballData = [
  {
    team1: "Team X",
    team2: "Team Y",
    date: "2 September, 05:00 pm",
    venue: "Arena 2",
    flag1: "/img/teamx.jpg",
    flag2: "/img/teamy.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team A",
    team2: "Team B",
    date: "4 September, 07:00 pm",
    venue: "Arena 3",
    flag1: "/img/teama.jpg",
    flag2: "/img/teamb.jpg",
    matchDetails: "Playoffs Round 1",
  },
  {
    team1: "Team C",
    team2: "Team D",
    date: "6 September, 06:00 pm",
    venue: "Arena 4",
    flag1: "/img/teamc.jpg",
    flag2: "/img/teamd.jpg",
    matchDetails: "Quarterfinal 2024",
  },
  {
    team1: "Team E",
    team2: "Team F",
    date: "8 September, 08:00 pm",
    venue: "Arena 5",
    flag1: "/img/teame.jpg",
    flag2: "/img/teamf.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team G",
    team2: "Team H",
    date: "10 September, 04:00 pm",
    venue: "Arena 6",
    flag1: "/img/teamg.jpg",
    flag2: "/img/teamh.jpg",
    matchDetails: "Semifinal 2024",
  },
  {
    team1: "Team I",
    team2: "Team J",
    date: "12 September, 07:00 pm",
    venue: "Arena 7",
    flag1: "/img/teami.jpg",
    flag2: "/img/teamj.jpg",
    matchDetails: "Final 2024",
  },
  {
    team1: "Team K",
    team2: "Team L",
    date: "14 September, 05:00 pm",
    venue: "Arena 8",
    flag1: "/img/teamk.jpg",
    flag2: "/img/teaml.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team M",
    team2: "Team N",
    date: "16 September, 09:00 pm",
    venue: "Arena 9",
    flag1: "/img/teamm.jpg",
    flag2: "/img/teamn.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team O",
    team2: "Team P",
    date: "18 September, 06:00 pm",
    venue: "Arena 10",
    flag1: "/img/teamo.jpg",
    flag2: "/img/teamp.jpg",
    matchDetails: "Friendly Match 2024",
  },
  {
    team1: "Team Q",
    team2: "Team R",
    date: "20 September, 08:00 pm",
    venue: "Arena 11",
    flag1: "/img/teamq.jpg",
    flag2: "/img/teamr.jpg",
    matchDetails: "Cup Final 2024",
  },
  {
    team1: "Team S",
    team2: "Team T",
    date: "22 September, 07:00 pm",
    venue: "Arena 12",
    flag1: "/img/teams.jpg",
    flag2: "/img/teamt.jpg",
    matchDetails: "Playoffs Round 2",
  },
  {
    team1: "Team U",
    team2: "Team V",
    date: "24 September, 06:00 pm",
    venue: "Arena 13",
    flag1: "/img/teamu.jpg",
    flag2: "/img/teamv.jpg",
    matchDetails: "Semifinal 2024",
  },
  {
    team1: "Team W",
    team2: "Team X",
    date: "26 September, 04:00 pm",
    venue: "Arena 14",
    flag1: "/img/teamw.jpg",
    flag2: "/img/teamx.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team Y",
    team2: "Team Z",
    date: "28 September, 05:00 pm",
    venue: "Arena 15",
    flag1: "/img/teamy.jpg",
    flag2: "/img/teamz.jpg",
    matchDetails: "Final 2024",
  },
  {
    team1: "Team AA",
    team2: "Team BB",
    date: "30 September, 08:00 pm",
    venue: "Arena 16",
    flag1: "/img/teamaa.jpg",
    flag2: "/img/teambb.jpg",
    matchDetails: "Friendly Match 2024",
  },
];

const hockeyData = [
  {
    team1: "Team M",
    team2: "Team N",
    date: "5 September, 08:00 pm",
    venue: "Hockey Stadium, City A",
    flag1: "/img/teamm.jpg",
    flag2: "/img/teamn.jpg",
    matchDetails: "National Championship 2024",
  },
  {
    team1: "Team A",
    team2: "Team B",
    date: "7 September, 07:00 pm",
    venue: "Hockey Arena, City B",
    flag1: "/img/teama.jpg",
    flag2: "/img/teamb.jpg",
    matchDetails: "Cup Final 2024",
  },
  {
    team1: "Team C",
    team2: "Team D",
    date: "9 September, 06:00 pm",
    venue: "Hockey Field, City C",
    flag1: "/img/teamc.jpg",
    flag2: "/img/teamd.jpg",
    matchDetails: "Semifinal 2024",
  },
  {
    team1: "Team E",
    team2: "Team F",
    date: "11 September, 05:00 pm",
    venue: "Hockey Ground, City D",
    flag1: "/img/teame.jpg",
    flag2: "/img/teamf.jpg",
    matchDetails: "Friendly Match 2024",
  },
  {
    team1: "Team G",
    team2: "Team H",
    date: "13 September, 04:00 pm",
    venue: "Hockey Stadium, City E",
    flag1: "/img/teamg.jpg",
    flag2: "/img/teamh.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team I",
    team2: "Team J",
    date: "15 September, 03:00 pm",
    venue: "Hockey Arena, City F",
    flag1: "/img/teami.jpg",
    flag2: "/img/teamj.jpg",
    matchDetails: "Cup Semifinal 2024",
  },
  {
    team1: "Team K",
    team2: "Team L",
    date: "17 September, 02:00 pm",
    venue: "Hockey Field, City G",
    flag1: "/img/teamk.jpg",
    flag2: "/img/teaml.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team M",
    team2: "Team N",
    date: "19 September, 01:00 pm",
    venue: "Hockey Ground, City H",
    flag1: "/img/teamm.jpg",
    flag2: "/img/teamn.jpg",
    matchDetails: "National Championship 2024",
  },
  {
    team1: "Team O",
    team2: "Team P",
    date: "21 September, 12:00 pm",
    venue: "Hockey Stadium, City I",
    flag1: "/img/teamo.jpg",
    flag2: "/img/teamp.jpg",
    matchDetails: "Cup Final 2024",
  },
  {
    team1: "Team Q",
    team2: "Team R",
    date: "23 September, 11:00 am",
    venue: "Hockey Arena, City J",
    flag1: "/img/teamq.jpg",
    flag2: "/img/teamr.jpg",
    matchDetails: "Friendly Match 2024",
  },
  {
    team1: "Team S",
    team2: "Team T",
    date: "25 September, 10:00 am",
    venue: "Hockey Field, City K",
    flag1: "/img/teams.jpg",
    flag2: "/img/teamt.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team U",
    team2: "Team V",
    date: "27 September, 09:00 am",
    venue: "Hockey Ground, City L",
    flag1: "/img/teamu.jpg",
    flag2: "/img/teamv.jpg",
    matchDetails: "Cup Final 2024",
  },
  {
    team1: "Team W",
    team2: "Team X",
    date: "29 September, 08:00 am",
    venue: "Hockey Stadium, City M",
    flag1: "/img/teamw.jpg",
    flag2: "/img/teamx.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team Y",
    team2: "Team Z",
    date: "1 October, 07:00 pm",
    venue: "Hockey Arena, City N",
    flag1: "/img/teamy.jpg",
    flag2: "/img/teamz.jpg",
    matchDetails: "Cup Semifinal 2024",
  },
  {
    team1: "Team AA",
    team2: "Team BB",
    date: "3 October, 06:00 pm",
    venue: "Hockey Field, City O",
    flag1: "/img/teamaa.jpg",
    flag2: "/img/teambb.jpg",
    matchDetails: "League Match 2024",
  },
];

const badmintonData = [
  {
    team1: "Player 1",
    team2: "Player 2",
    date: "10 September, 10:00 am",
    venue: "Badminton Hall, City B",
    flag1: "/img/player1.jpg",
    flag2: "/img/player2.jpg",
    matchDetails: "Open Championship 2024",
  },
  {
    team1: "Player 3",
    team2: "Player 4",
    date: "12 September, 11:00 am",
    venue: "Badminton Court, City C",
    flag1: "/img/player3.jpg",
    flag2: "/img/player4.jpg",
    matchDetails: "National Championship 2024",
  },
  {
    team1: "Player 5",
    team2: "Player 6",
    date: "14 September, 12:00 pm",
    venue: "Badminton Arena, City D",
    flag1: "/img/player5.jpg",
    flag2: "/img/player6.jpg",
    matchDetails: "International Match 2024",
  },
  {
    team1: "Player 7",
    team2: "Player 8",
    date: "16 September, 01:00 pm",
    venue: "Badminton Hall, City E",
    flag1: "/img/player7.jpg",
    flag2: "/img/player8.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Player 9",
    team2: "Player 10",
    date: "18 September, 02:00 pm",
    venue: "Badminton Court, City F",
    flag1: "/img/player9.jpg",
    flag2: "/img/player10.jpg",
    matchDetails: "Open Championship 2024",
  },
  {
    team1: "Player 11",
    team2: "Player 12",
    date: "20 September, 03:00 pm",
    venue: "Badminton Arena, City G",
    flag1: "/img/player11.jpg",
    flag2: "/img/player12.jpg",
    matchDetails: "National Championship 2024",
  },
  {
    team1: "Player 13",
    team2: "Player 14",
    date: "22 September, 04:00 pm",
    venue: "Badminton Hall, City H",
    flag1: "/img/player13.jpg",
    flag2: "/img/player14.jpg",
    matchDetails: "International Match 2024",
  },
  {
    team1: "Player 15",
    team2: "Player 16",
    date: "24 September, 05:00 pm",
    venue: "Badminton Court, City I",
    flag1: "/img/player15.jpg",
    flag2: "/img/player16.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Player 17",
    team2: "Player 18",
    date: "26 September, 06:00 pm",
    venue: "Badminton Arena, City J",
    flag1: "/img/player17.jpg",
    flag2: "/img/player18.jpg",
    matchDetails: "Open Championship 2024",
  },
  {
    team1: "Player 19",
    team2: "Player 20",
    date: "28 September, 07:00 pm",
    venue: "Badminton Hall, City K",
    flag1: "/img/player19.jpg",
    flag2: "/img/player20.jpg",
    matchDetails: "National Championship 2024",
  },
  {
    team1: "Player 21",
    team2: "Player 22",
    date: "30 September, 08:00 pm",
    venue: "Badminton Court, City L",
    flag1: "/img/player21.jpg",
    flag2: "/img/player22.jpg",
    matchDetails: "International Match 2024",
  },
  {
    team1: "Player 23",
    team2: "Player 24",
    date: "2 October, 09:00 am",
    venue: "Badminton Arena, City M",
    flag1: "/img/player23.jpg",
    flag2: "/img/player24.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Player 25",
    team2: "Player 26",
    date: "4 October, 10:00 am",
    venue: "Badminton Hall, City N",
    flag1: "/img/player25.jpg",
    flag2: "/img/player26.jpg",
    matchDetails: "Open Championship 2024",
  },
  {
    team1: "Player 27",
    team2: "Player 28",
    date: "6 October, 11:00 am",
    venue: "Badminton Court, City O",
    flag1: "/img/player27.jpg",
    flag2: "/img/player28.jpg",
    matchDetails: "National Championship 2024",
  },
  {
    team1: "Player 29",
    team2: "Player 30",
    date: "8 October, 12:00 pm",
    venue: "Badminton Arena, City P",
    flag1: "/img/player29.jpg",
    flag2: "/img/player30.jpg",
    matchDetails: "International Match 2024",
  },
];

const tennisData = [
  {
    team1: "Player A",
    team2: "Player B",
    date: "15 September, 02:00 pm",
    venue: "Tennis Court, City C",
    flag1: "/img/playera.jpg",
    flag2: "/img/playerb.jpg",
    matchDetails: "Grand Slam Final 2024",
  },
  {
    team1: "Player C",
    team2: "Player D",
    date: "17 September, 04:00 pm",
    venue: "Clay Court, City D",
    flag1: "/img/playerc.jpg",
    flag2: "/img/playerd.jpg",
    matchDetails: "Clay Court Championship 2024",
  },
  {
    team1: "Player E",
    team2: "Player F",
    date: "19 September, 03:00 pm",
    venue: "Hard Court, City E",
    flag1: "/img/playere.jpg",
    flag2: "/img/playerf.jpg",
    matchDetails: "Hard Court Open 2024",
  },
  {
    team1: "Player G",
    team2: "Player H",
    date: "21 September, 01:00 pm",
    venue: "Grass Court, City F",
    flag1: "/img/playerg.jpg",
    flag2: "/img/playerh.jpg",
    matchDetails: "Grass Court Championship 2024",
  },
  {
    team1: "Player I",
    team2: "Player J",
    date: "23 September, 05:00 pm",
    venue: "Indoor Court, City G",
    flag1: "/img/playeri.jpg",
    flag2: "/img/playerj.jpg",
    matchDetails: "Indoor Masters 2024",
  },
  {
    team1: "Player K",
    team2: "Player L",
    date: "25 September, 12:00 pm",
    venue: "Tennis Center, City H",
    flag1: "/img/playerk.jpg",
    flag2: "/img/playerl.jpg",
    matchDetails: "National Open 2024",
  },
  {
    team1: "Player M",
    team2: "Player N",
    date: "27 September, 06:00 pm",
    venue: "Stadium, City I",
    flag1: "/img/playerm.jpg",
    flag2: "/img/playern.jpg",
    matchDetails: "International Tennis Classic 2024",
  },
  {
    team1: "Player O",
    team2: "Player P",
    date: "29 September, 03:00 pm",
    venue: "City Tennis Club, City J",
    flag1: "/img/playero.jpg",
    flag2: "/img/playerp.jpg",
    matchDetails: "City Championship 2024",
  },
  {
    team1: "Player Q",
    team2: "Player R",
    date: "1 October, 11:00 am",
    venue: "Regional Court, City K",
    flag1: "/img/playerq.jpg",
    flag2: "/img/playerr.jpg",
    matchDetails: "Regional Open 2024",
  },
  {
    team1: "Player S",
    team2: "Player T",
    date: "3 October, 04:00 pm",
    venue: "National Arena, City L",
    flag1: "/img/players.jpg",
    flag2: "/img/playert.jpg",
    matchDetails: "National Cup 2024",
  },
  {
    team1: "Player U",
    team2: "Player V",
    date: "5 October, 01:00 pm",
    venue: "International Court, City M",
    flag1: "/img/playeru.jpg",
    flag2: "/img/playerv.jpg",
    matchDetails: "World Tennis Tour 2024",
  },
  {
    team1: "Player W",
    team2: "Player X",
    date: "7 October, 02:00 pm",
    venue: "Arena, City N",
    flag1: "/img/playerw.jpg",
    flag2: "/img/playerx.jpg",
    matchDetails: "Arena Championship 2024",
  },
  {
    team1: "Player Y",
    team2: "Player Z",
    date: "9 October, 05:00 pm",
    venue: "Grand Slam Arena, City O",
    flag1: "/img/playery.jpg",
    flag2: "/img/playerz.jpg",
    matchDetails: "Grand Slam Quarterfinal 2024",
  },
];

const tableTennisData = [
  {
    team1: "Player X",
    team2: "Player Y",
    date: "20 September, 11:00 am",
    venue: "Table Tennis Arena, City D",
    flag1: "/img/playerx.jpg",
    flag2: "/img/playery.jpg",
    matchDetails: "World Championship 2024",
  },
  {
    team1: "Player A",
    team2: "Player B",
    date: "22 September, 02:00 pm",
    venue: "Indoor Stadium, City E",
    flag1: "/img/playera.jpg",
    flag2: "/img/playerb.jpg",
    matchDetails: "Continental Cup 2024",
  },
  {
    team1: "Player C",
    team2: "Player D",
    date: "24 September, 04:00 pm",
    venue: "Sports Complex, City F",
    flag1: "/img/playerc.jpg",
    flag2: "/img/playerd.jpg",
    matchDetails: "Open Invitational 2024",
  },
  {
    team1: "Player E",
    team2: "Player F",
    date: "26 September, 01:00 pm",
    venue: "Table Tennis Hall, City G",
    flag1: "/img/playere.jpg",
    flag2: "/img/playerf.jpg",
    matchDetails: "City Championship 2024",
  },
  {
    team1: "Player G",
    team2: "Player H",
    date: "28 September, 03:00 pm",
    venue: "National Arena, City H",
    flag1: "/img/playerg.jpg",
    flag2: "/img/playerh.jpg",
    matchDetails: "National Open 2024",
  },
  {
    team1: "Player I",
    team2: "Player J",
    date: "30 September, 05:00 pm",
    venue: "International Venue, City I",
    flag1: "/img/playeri.jpg",
    flag2: "/img/playerj.jpg",
    matchDetails: "International Series 2024",
  },
  {
    team1: "Player K",
    team2: "Player L",
    date: "2 October, 11:00 am",
    venue: "Sports Hall, City J",
    flag1: "/img/playerk.jpg",
    flag2: "/img/playerl.jpg",
    matchDetails: "Regional Qualifiers 2024",
  },
  {
    team1: "Player M",
    team2: "Player N",
    date: "4 October, 02:00 pm",
    venue: "Community Center, City K",
    flag1: "/img/playerm.jpg",
    flag2: "/img/playern.jpg",
    matchDetails: "Community Cup 2024",
  },
  {
    team1: "Player O",
    team2: "Player P",
    date: "6 October, 04:00 pm",
    venue: "Arena, City L",
    flag1: "/img/playero.jpg",
    flag2: "/img/playerp.jpg",
    matchDetails: "Super Series 2024",
  },
  {
    team1: "Player Q",
    team2: "Player R",
    date: "8 October, 01:00 pm",
    venue: "Table Tennis Club, City M",
    flag1: "/img/playerq.jpg",
    flag2: "/img/playerr.jpg",
    matchDetails: "City Open 2024",
  },
  {
    team1: "Player S",
    team2: "Player T",
    date: "10 October, 05:00 pm",
    venue: "University Hall, City N",
    flag1: "/img/players.jpg",
    flag2: "/img/playert.jpg",
    matchDetails: "University League 2024",
  },
  {
    team1: "Player U",
    team2: "Player V",
    date: "12 October, 11:00 am",
    venue: "Training Center, City O",
    flag1: "/img/playeru.jpg",
    flag2: "/img/playerv.jpg",
    matchDetails: "Training Center Cup 2024",
  },
  {
    team1: "Player W",
    team2: "Player X",
    date: "14 October, 02:00 pm",
    venue: "Recreation Center, City P",
    flag1: "/img/playerw.jpg",
    flag2: "/img/playerx.jpg",
    matchDetails: "Recreation Tournament 2024",
  },
  {
    team1: "Player Y",
    team2: "Player Z",
    date: "16 October, 04:00 pm",
    venue: "Downtown Arena, City Q",
    flag1: "/img/playery.jpg",
    flag2: "/img/playerz.jpg",
    matchDetails: "Downtown Championship 2024",
  },
  {
    team1: "Player AA",
    team2: "Player BB",
    date: "18 October, 06:00 pm",
    venue: "Sports Village, City R",
    flag1: "/img/playeraa.jpg",
    flag2: "/img/playerbb.jpg",
    matchDetails: "Sports Village Open 2024",
  },
];

const iceHockeyData = [
  {
    team1: "Team I",
    team2: "Team J",
    date: "25 September, 09:00 pm",
    venue: "Ice Rink, City E",
    flag1: "/img/teami.jpg",
    flag2: "/img/teamj.jpg",
    matchDetails: "Winter Games 2024",
  },
  {
    team1: "Team A",
    team2: "Team B",
    date: "27 September, 07:00 pm",
    venue: "Ice Arena, City F",
    flag1: "/img/teama.jpg",
    flag2: "/img/teamb.jpg",
    matchDetails: "Championship Match 2024",
  },
  {
    team1: "Team C",
    team2: "Team D",
    date: "29 September, 08:00 pm",
    venue: "Hockey Rink, City G",
    flag1: "/img/teamc.jpg",
    flag2: "/img/teamd.jpg",
    matchDetails: "League Match 2024",
  },
  {
    team1: "Team E",
    team2: "Team F",
    date: "1 October, 06:00 pm",
    venue: "Skating Rink, City H",
    flag1: "/img/teame.jpg",
    flag2: "/img/teamf.jpg",
    matchDetails: "International Cup 2024",
  },
  {
    team1: "Team G",
    team2: "Team H",
    date: "3 October, 05:00 pm",
    venue: "Ice Palace, City I",
    flag1: "/img/teamg.jpg",
    flag2: "/img/teamh.jpg",
    matchDetails: "Ice Hockey Classic 2024",
  },
  {
    team1: "Team K",
    team2: "Team L",
    date: "5 October, 04:00 pm",
    venue: "Winter Sports Center, City J",
    flag1: "/img/teamk.jpg",
    flag2: "/img/teaml.jpg",
    matchDetails: "Snow Cup 2024",
  },
  {
    team1: "Team M",
    team2: "Team N",
    date: "7 October, 03:00 pm",
    venue: "Frozen Arena, City K",
    flag1: "/img/teamm.jpg",
    flag2: "/img/teamn.jpg",
    matchDetails: "Glacier Trophy 2024",
  },
  {
    team1: "Team O",
    team2: "Team P",
    date: "9 October, 08:00 pm",
    venue: "Icy Stadium, City L",
    flag1: "/img/teamo.jpg",
    flag2: "/img/teamp.jpg",
    matchDetails: "Frost Cup 2024",
  },
  {
    team1: "Team Q",
    team2: "Team R",
    date: "11 October, 07:00 pm",
    venue: "Arctic Arena, City M",
    flag1: "/img/teamq.jpg",
    flag2: "/img/teamr.jpg",
    matchDetails: "Polar Challenge 2024",
  },
  {
    team1: "Team S",
    team2: "Team T",
    date: "13 October, 06:00 pm",
    venue: "Cold Dome, City N",
    flag1: "/img/teams.jpg",
    flag2: "/img/teamt.jpg",
    matchDetails: "Ice Shield 2024",
  },
  {
    team1: "Team U",
    team2: "Team V",
    date: "15 October, 05:00 pm",
    venue: "Frosty Field, City O",
    flag1: "/img/teamu.jpg",
    flag2: "/img/teamv.jpg",
    matchDetails: "Snowstorm Series 2024",
  },
  {
    team1: "Team W",
    team2: "Team X",
    date: "17 October, 09:00 pm",
    venue: "Ice Zone, City P",
    flag1: "/img/teamw.jpg",
    flag2: "/img/teamx.jpg",
    matchDetails: "Blizzard Cup 2024",
  },
  {
    team1: "Team Y",
    team2: "Team Z",
    date: "19 October, 08:00 pm",
    venue: "Ice Fortress, City Q",
    flag1: "/img/teamy.jpg",
    flag2: "/img/teamz.jpg",
    matchDetails: "Frozen Classic 2024",
  },
  {
    team1: "Team AA",
    team2: "Team BB",
    date: "21 October, 07:00 pm",
    venue: "Winter Palace, City R",
    flag1: "/img/teamaa.jpg",
    flag2: "/img/teambb.jpg",
    matchDetails: "Cold War Series 2024",
  },
  {
    team1: "Team CC",
    team2: "Team DD",
    date: "23 October, 06:00 pm",
    venue: "Snowy Stadium, City S",
    flag1: "/img/teamcc.jpg",
    flag2: "/img/teamdd.jpg",
    matchDetails: "Glacial Showdown 2024",
  },
];

const snookerData = [
  {
    team1: "Player 1",
    team2: "Player 2",
    date: "30 September, 07:00 pm",
    venue: "Snooker Club, City F",
    flag1: "/img/snooker1.jpg",
    flag2: "/img/snooker2.jpg",
    matchDetails: "World Snooker Championship 2024",
  },
  {
    team1: "Player A",
    team2: "Player B",
    date: "2 October, 06:00 pm",
    venue: "Billiards Hall, City G",
    flag1: "/img/snooker3.jpg",
    flag2: "/img/snooker4.jpg",
    matchDetails: "International Snooker Open 2024",
  },
  {
    team1: "Player C",
    team2: "Player D",
    date: "4 October, 08:00 pm",
    venue: "Cue Club, City H",
    flag1: "/img/snooker5.jpg",
    flag2: "/img/snooker6.jpg",
    matchDetails: "Pro Snooker Series 2024",
  },
  {
    team1: "Player E",
    team2: "Player F",
    date: "6 October, 05:00 pm",
    venue: "Snooker Arena, City I",
    flag1: "/img/snooker7.jpg",
    flag2: "/img/snooker8.jpg",
    matchDetails: "Masters Tournament 2024",
  },
  {
    team1: "Player G",
    team2: "Player H",
    date: "8 October, 04:00 pm",
    venue: "Pool House, City J",
    flag1: "/img/snooker9.jpg",
    flag2: "/img/snooker10.jpg",
    matchDetails: "Grand Slam of Snooker 2024",
  },
  {
    team1: "Player I",
    team2: "Player J",
    date: "10 October, 07:00 pm",
    venue: "Snooker Centre, City K",
    flag1: "/img/snooker11.jpg",
    flag2: "/img/snooker12.jpg",
    matchDetails: "National Snooker Championship 2024",
  },
  {
    team1: "Player K",
    team2: "Player L",
    date: "12 October, 06:00 pm",
    venue: "Cue Masters, City L",
    flag1: "/img/snooker13.jpg",
    flag2: "/img/snooker14.jpg",
    matchDetails: "Snooker World Series 2024",
  },
  {
    team1: "Player M",
    team2: "Player N",
    date: "14 October, 08:00 pm",
    venue: "Snooker Palace, City M",
    flag1: "/img/snooker15.jpg",
    flag2: "/img/snooker16.jpg",
    matchDetails: "Cue Sports Championship 2024",
  },
  {
    team1: "Player O",
    team2: "Player P",
    date: "16 October, 05:00 pm",
    venue: "Billiard Centre, City N",
    flag1: "/img/snooker17.jpg",
    flag2: "/img/snooker18.jpg",
    matchDetails: "International Masters 2024",
  },
  {
    team1: "Player Q",
    team2: "Player R",
    date: "18 October, 04:00 pm",
    venue: "Snooker Hall, City O",
    flag1: "/img/snooker19.jpg",
    flag2: "/img/snooker20.jpg",
    matchDetails: "World Cup of Snooker 2024",
  },
  {
    team1: "Player S",
    team2: "Player T",
    date: "20 October, 07:00 pm",
    venue: "The Green Room, City P",
    flag1: "/img/snooker21.jpg",
    flag2: "/img/snooker22.jpg",
    matchDetails: "Premier Snooker League 2024",
  },
  {
    team1: "Player U",
    team2: "Player V",
    date: "22 October, 06:00 pm",
    venue: "Champions Snooker Club, City Q",
    flag1: "/img/snooker23.jpg",
    flag2: "/img/snooker24.jpg",
    matchDetails: "Cue Masters Invitational 2024",
  },
  {
    team1: "Player W",
    team2: "Player X",
    date: "24 October, 08:00 pm",
    venue: "Snooker Kingdom, City R",
    flag1: "/img/snooker25.jpg",
    flag2: "/img/snooker26.jpg",
    matchDetails: "Global Snooker Series 2024",
  },
  {
    team1: "Player Y",
    team2: "Player Z",
    date: "26 October, 05:00 pm",
    venue: "Billiards & Snooker Club, City S",
    flag1: "/img/snooker27.jpg",
    flag2: "/img/snooker28.jpg",
    matchDetails: "Elite Snooker Championship 2024",
  },
  {
    team1: "Player AA",
    team2: "Player BB",
    date: "28 October, 04:00 pm",
    venue: "World Snooker Complex, City T",
    flag1: "/img/snooker29.jpg",
    flag2: "/img/snooker30.jpg",
    matchDetails: "World Ranking Event 2024",
  },
];


const poloData = [
  {
    team1: "Team X",
    team2: "Team Y",
    date: "5 October, 03:00 pm",
    venue: "Polo Field, City G",
    flag1: "/img/polo1.jpg",
    flag2: "/img/polo2.jpg",
    matchDetails: "Polo Cup 2024",
  },
  {
    team1: "Team A",
    team2: "Team B",
    date: "7 October, 04:00 pm",
    venue: "Polo Grounds, City H",
    flag1: "/img/polo3.jpg",
    flag2: "/img/polo4.jpg",
    matchDetails: "National Polo League 2024",
  },
  {
    team1: "Team C",
    team2: "Team D",
    date: "9 October, 02:00 pm",
    venue: "Royal Polo Club, City I",
    flag1: "/img/polo5.jpg",
    flag2: "/img/polo6.jpg",
    matchDetails: "International Polo Challenge 2024",
  },
  {
    team1: "Team E",
    team2: "Team F",
    date: "11 October, 05:00 pm",
    venue: "Polo Arena, City J",
    flag1: "/img/polo7.jpg",
    flag2: "/img/polo8.jpg",
    matchDetails: "Polo Masters Tournament 2024",
  },
  {
    team1: "Team G",
    team2: "Team H",
    date: "13 October, 03:00 pm",
    venue: "Grand Polo Grounds, City K",
    flag1: "/img/polo9.jpg",
    flag2: "/img/polo10.jpg",
    matchDetails: "Polo World Series 2024",
  },
  {
    team1: "Team I",
    team2: "Team J",
    date: "15 October, 04:00 pm",
    venue: "Polo Park, City L",
    flag1: "/img/polo11.jpg",
    flag2: "/img/polo12.jpg",
    matchDetails: "Continental Polo Championship 2024",
  },
  {
    team1: "Team K",
    team2: "Team L",
    date: "17 October, 02:00 pm",
    venue: "Elite Polo Club, City M",
    flag1: "/img/polo13.jpg",
    flag2: "/img/polo14.jpg",
    matchDetails: "Polo Premier League 2024",
  },
  {
    team1: "Team M",
    team2: "Team N",
    date: "19 October, 05:00 pm",
    venue: "Polo Park, City N",
    flag1: "/img/polo15.jpg",
    flag2: "/img/polo16.jpg",
    matchDetails: "Global Polo Championship 2024",
  },
  {
    team1: "Team O",
    team2: "Team P",
    date: "21 October, 03:00 pm",
    venue: "Polo Arena, City O",
    flag1: "/img/polo17.jpg",
    flag2: "/img/polo18.jpg",
    matchDetails: "Polo Challenge Cup 2024",
  },
  {
    team1: "Team Q",
    team2: "Team R",
    date: "23 October, 04:00 pm",
    venue: "Polo Fields, City P",
    flag1: "/img/polo19.jpg",
    flag2: "/img/polo20.jpg",
    matchDetails: "Intercontinental Polo Cup 2024",
  },
  {
    team1: "Team S",
    team2: "Team T",
    date: "25 October, 02:00 pm",
    venue: "Polo Club, City Q",
    flag1: "/img/polo21.jpg",
    flag2: "/img/polo22.jpg",
    matchDetails: "Polo Grand Prix 2024",
  },
  {
    team1: "Team U",
    team2: "Team V",
    date: "27 October, 05:00 pm",
    venue: "Polo Park, City R",
    flag1: "/img/polo23.jpg",
    flag2: "/img/polo24.jpg",
    matchDetails: "Polo Elite Series 2024",
  },
  {
    team1: "Team W",
    team2: "Team X",
    date: "29 October, 03:00 pm",
    venue: "Polo Grounds, City S",
    flag1: "/img/polo25.jpg",
    flag2: "/img/polo26.jpg",
    matchDetails: "International Polo League 2024",
  },
  {
    team1: "Team Y",
    team2: "Team Z",
    date: "31 October, 04:00 pm",
    venue: "Polo Field, City T",
    flag1: "/img/polo27.jpg",
    flag2: "/img/polo28.jpg",
    matchDetails: "Polo World Cup 2024",
  },
  {
    team1: "Team AA",
    team2: "Team BB",
    date: "2 November, 02:00 pm",
    venue: "Polo Arena, City U",
    flag1: "/img/polo29.jpg",
    flag2: "/img/polo30.jpg",
    matchDetails: "Polo Nations Cup 2024",
  },
];

const tentPeggingData = [
  {
    team1: "Rider A",
    team2: "Rider B",
    date: "10 October, 04:00 pm",
    venue: "Tent Pegging Ground, City H",
    flag1: "/img/ridera.jpg",
    flag2: "/img/riderb.jpg",
    matchDetails: "National Tent Pegging Championship 2024",
  },
  {
    team1: "Rider C",
    team2: "Rider D",
    date: "12 October, 05:00 pm",
    venue: "Tent Pegging Arena, City I",
    flag1: "/img/riderc.jpg",
    flag2: "/img/riderd.jpg",
    matchDetails: "Regional Tent Pegging Cup 2024",
  },
  {
    team1: "Rider E",
    team2: "Rider F",
    date: "14 October, 06:00 pm",
    venue: "Tent Pegging Field, City J",
    flag1: "/img/ridere.jpg",
    flag2: "/img/riderf.jpg",
    matchDetails: "Tent Pegging Open 2024",
  },
  {
    team1: "Rider G",
    team2: "Rider H",
    date: "16 October, 04:00 pm",
    venue: "Tent Pegging Grounds, City K",
    flag1: "/img/riderg.jpg",
    flag2: "/img/riderh.jpg",
    matchDetails: "Tent Pegging Festival 2024",
  },
  {
    team1: "Rider I",
    team2: "Rider J",
    date: "18 October, 05:00 pm",
    venue: "Tent Pegging Complex, City L",
    flag1: "/img/rideri.jpg",
    flag2: "/img/riderj.jpg",
    matchDetails: "International Tent Pegging Tournament 2024",
  },
  {
    team1: "Rider K",
    team2: "Rider L",
    date: "20 October, 06:00 pm",
    venue: "Tent Pegging Park, City M",
    flag1: "/img/riderk.jpg",
    flag2: "/img/riderl.jpg",
    matchDetails: "Tent Pegging Masters 2024",
  },
  {
    team1: "Rider M",
    team2: "Rider N",
    date: "22 October, 04:00 pm",
    venue: "Tent Pegging Stadium, City N",
    flag1: "/img/riderm.jpg",
    flag2: "/img/ridern.jpg",
    matchDetails: "Tent Pegging Challenge 2024",
  },
  {
    team1: "Rider O",
    team2: "Rider P",
    date: "24 October, 05:00 pm",
    venue: "Tent Pegging Arena, City O",
    flag1: "/img/ridero.jpg",
    flag2: "/img/riderp.jpg",
    matchDetails: "Tent Pegging Elite Cup 2024",
  },
  {
    team1: "Rider Q",
    team2: "Rider R",
    date: "26 October, 06:00 pm",
    venue: "Tent Pegging Field, City P",
    flag1: "/img/riderq.jpg",
    flag2: "/img/riderr.jpg",
    matchDetails: "Tent Pegging World Series 2024",
  },
  {
    team1: "Rider S",
    team2: "Rider T",
    date: "28 October, 04:00 pm",
    venue: "Tent Pegging Grounds, City Q",
    flag1: "/img/riders.jpg",
    flag2: "/img/ridert.jpg",
    matchDetails: "National Tent Pegging League 2024",
  },
  {
    team1: "Rider U",
    team2: "Rider V",
    date: "30 October, 05:00 pm",
    venue: "Tent Pegging Center, City R",
    flag1: "/img/rideru.jpg",
    flag2: "/img/riderv.jpg",
    matchDetails: "Tent Pegging Cup 2024",
  },
  {
    team1: "Rider W",
    team2: "Rider X",
    date: "1 November, 06:00 pm",
    venue: "Tent Pegging Stadium, City S",
    flag1: "/img/riderw.jpg",
    flag2: "/img/riderx.jpg",
    matchDetails: "Tent Pegging Championship 2024",
  },
  {
    team1: "Rider Y",
    team2: "Rider Z",
    date: "3 November, 04:00 pm",
    venue: "Tent Pegging Arena, City T",
    flag1: "/img/ridery.jpg",
    flag2: "/img/riderz.jpg",
    matchDetails: "Tent Pegging International 2024",
  },
  {
    team1: "Rider AA",
    team2: "Rider BB",
    date: "5 November, 05:00 pm",
    venue: "Tent Pegging Park, City U",
    flag1: "/img/rideraa.jpg",
    flag2: "/img/riderbb.jpg",
    matchDetails: "Tent Pegging Festival 2024",
  },
  {
    team1: "Rider CC",
    team2: "Rider DD",
    date: "7 November, 06:00 pm",
    venue: "Tent Pegging Field, City V",
    flag1: "/img/ridercc.jpg",
    flag2: "/img/riderdd.jpg",
    matchDetails: "Tent Pegging Open 2024",
  },
  {
    team1: "Rider EE",
    team2: "Rider FF",
    date: "9 November, 04:00 pm",
    venue: "Tent Pegging Complex, City W",
    flag1: "/img/rideree.jpg",
    flag2: "/img/riderff.jpg",
    matchDetails: "Tent Pegging Challenge 2024",
  },
];


const kabaddiData = [
  {
    team1: "Team Alpha",
    team2: "Team Beta",
    date: "15 October, 05:00 pm",
    venue: "Kabaddi Stadium, City I",
    flag1: "/img/alpha.jpg",
    flag2: "/img/beta.jpg",
    matchDetails: "Kabaddi World Cup 2024",
  },
  {
    team1: "Team Gamma",
    team2: "Team Delta",
    date: "17 October, 06:00 pm",
    venue: "Kabaddi Arena, City J",
    flag1: "/img/gamma.jpg",
    flag2: "/img/delta.jpg",
    matchDetails: "National Kabaddi League 2024",
  },
  {
    team1: "Team Epsilon",
    team2: "Team Zeta",
    date: "19 October, 04:00 pm",
    venue: "Kabaddi Ground, City K",
    flag1: "/img/epsilon.jpg",
    flag2: "/img/zeta.jpg",
    matchDetails: "Kabaddi Championship 2024",
  },
  {
    team1: "Team Eta",
    team2: "Team Theta",
    date: "21 October, 05:00 pm",
    venue: "Kabaddi Stadium, City L",
    flag1: "/img/eta.jpg",
    flag2: "/img/theta.jpg",
    matchDetails: "Pro Kabaddi League 2024",
  },
  {
    team1: "Team Iota",
    team2: "Team Kappa",
    date: "23 October, 06:00 pm",
    venue: "Kabaddi Center, City M",
    flag1: "/img/iota.jpg",
    flag2: "/img/kappa.jpg",
    matchDetails: "International Kabaddi Series 2024",
  },
  {
    team1: "Team Lambda",
    team2: "Team Mu",
    date: "25 October, 04:00 pm",
    venue: "Kabaddi Arena, City N",
    flag1: "/img/lambda.jpg",
    flag2: "/img/mu.jpg",
    matchDetails: "Kabaddi Premier Tournament 2024",
  },
  {
    team1: "Team Nu",
    team2: "Team Xi",
    date: "27 October, 05:00 pm",
    venue: "Kabaddi Field, City O",
    flag1: "/img/nu.jpg",
    flag2: "/img/xi.jpg",
    matchDetails: "Kabaddi Elite Cup 2024",
  },
  {
    team1: "Team Omicron",
    team2: "Team Pi",
    date: "29 October, 06:00 pm",
    venue: "Kabaddi Stadium, City P",
    flag1: "/img/omicron.jpg",
    flag2: "/img/pi.jpg",
    matchDetails: "World Kabaddi Series 2024",
  },
  {
    team1: "Team Rho",
    team2: "Team Sigma",
    date: "31 October, 04:00 pm",
    venue: "Kabaddi Grounds, City Q",
    flag1: "/img/rho.jpg",
    flag2: "/img/sigma.jpg",
    matchDetails: "Kabaddi Nations Cup 2024",
  },
  {
    team1: "Team Tau",
    team2: "Team Upsilon",
    date: "2 November, 05:00 pm",
    venue: "Kabaddi Park, City R",
    flag1: "/img/tau.jpg",
    flag2: "/img/upsilon.jpg",
    matchDetails: "Global Kabaddi Championship 2024",
  },
  {
    team1: "Team Phi",
    team2: "Team Chi",
    date: "4 November, 06:00 pm",
    venue: "Kabaddi Arena, City S",
    flag1: "/img/phi.jpg",
    flag2: "/img/chi.jpg",
    matchDetails: "Kabaddi Super Series 2024",
  },
  {
    team1: "Team Psi",
    team2: "Team Omega",
    date: "6 November, 04:00 pm",
    venue: "Kabaddi Stadium, City T",
    flag1: "/img/psi.jpg",
    flag2: "/img/omega.jpg",
    matchDetails: "Intercontinental Kabaddi Cup 2024",
  },
  {
    team1: "Team Alpha 2",
    team2: "Team Beta 2",
    date: "8 November, 05:00 pm",
    venue: "Kabaddi Grounds, City U",
    flag1: "/img/alpha2.jpg",
    flag2: "/img/beta2.jpg",
    matchDetails: "Kabaddi World Tour 2024",
  },
  {
    team1: "Team Gamma 2",
    team2: "Team Delta 2",
    date: "10 November, 06:00 pm",
    venue: "Kabaddi Center, City V",
    flag1: "/img/gamma2.jpg",
    flag2: "/img/delta2.jpg",
    matchDetails: "National Kabaddi Tournament 2024",
  },
  {
    team1: "Team Epsilon 2",
    team2: "Team Zeta 2",
    date: "12 November, 04:00 pm",
    venue: "Kabaddi Park, City W",
    flag1: "/img/epsilon2.jpg",
    flag2: "/img/zeta2.jpg",
    matchDetails: "Kabaddi Masters League 2024",
  },
];



export {
  cricketData,
  footballData,
  basketballData,
  hockeyData,
  badmintonData,
  tennisData,
  tableTennisData,
  iceHockeyData,
  snookerData,
  poloData,
  tentPeggingData,
  kabaddiData,
};


