import React from 'react';
import '../Style/Scorecard.css'; // Import the CSS file
import { generateRows } from '../Helper/ScoreData'; // Import the mapping function
import { generateRows2 } from '../Helper/ScoreData2'; // Import the additional mapping function

const Scorecard = () => {
  return React.createElement(
    'div',
    { className: 'universal-box' },
    React.createElement(
      'section',
      { className: 'box-with-border' },
      React.createElement(
        'header',
        { className: 'text-container' },
        React.createElement('h4', null, 'Eng'),
        React.createElement('p', null, '(20 ovs maximum)')
      ),
      ...generateRows(), // Spread the rows generated by the mapping function

      React.createElement('br'),
      React.createElement('br'),
      React.createElement(
        'header',
        { className: 'text-container' },
        React.createElement('h4', null, 'PAK'),
        React.createElement('p', null, '(T: 131 runs from 20 ovs)')
      ),
      ...generateRows2() // Add another set of rows
    )
  );
};

export default Scorecard;
